### ISSUE TITLE
打开小说会报错

### ISSUE THREAD

**Issue by miantanjun** [iryan53/TouchFish#1]
![image](https://github.com/iryan53/TouchFish/assets/102712739/122bdb05-a52b-4d9b-862e-4ed292f277c4)

打开会报错这个

**Comment by iryan53** [comment]
感谢你的反馈，以下可能是原因：
1. TXT文件非原生TXT，可能是别的格式通过修改后缀“强行”更改成的。
2. 此TXT文件少于2001字（页数算法问题，后续版本优化算法后会解决）
3. 文件路径存在中文或符号（小概率）

如果上述情况都不符合的话再请你把完整的错误信息发一下哦

**Comment by miantanjun** [comment]
> 感谢你的反馈，以下可能是原因：
> 
> 1. TXT文件非原生TXT，可能是别的格式通过修改后缀“强行”更改成的。
> 2. 此TXT文件少于2001字（页数算法问题，后续版本优化算法后会解决）
> 3. 文件路径存在中文或符号（小概率）
> 
> 如果上述情况都不符合的话再请你把完整的错误信息发一下哦

具体报错如下：************** 异常文本 **************
System.ArgumentOutOfRangeException: StartIndex cannot be less than zero. (Parameter 'startIndex')
   at System.String.Remove(Int32 startIndex)
   at TouchFish.readerForm._Lambda$__156-1() in E:\VSProjects\TouchFish\readerForm.vb:line 178
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
--- End of stack trace from previous location ---
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Action method)
   at TouchFish.readerForm.bufferToRead() in E:\VSProjects\TouchFish\readerForm.vb:line 178
   at TouchFish.readerForm.generateBuffer() in E:\VSProjects\TouchFish\readerForm.vb:line 136
   at TouchFish.readerForm.readerForm_Load(Object sender, EventArgs e) in E:\VSProjects\TouchFish\readerForm.vb:line 365
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)


************** 已加载的程序集 **************
System.Private.CoreLib
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
TouchFish
    程序集版本:1.0.4.1
    Win32 版本:不可用
    代码库:
----------------------------------------
Microsoft.VisualBasic.Forms
    程序集版本:6.0.2.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Runtime
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Windows.Forms.Primitives
    程序集版本:6.0.2.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Windows.Forms
    程序集版本:6.0.2.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Diagnostics.TraceSource
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Collections
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.ComponentModel.Primitives
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Runtime.InteropServices
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Drawing.Primitives
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Collections.Specialized
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Security.Principal.Windows
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Security.Claims
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
Microsoft.Win32.Primitives
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Threading.Thread
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.ComponentModel.EventBasedAsync
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Threading
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.IO.Pipes
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Security.AccessControl
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Threading.Overlapped
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.ComponentModel
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Drawing.Common
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
Accessibility
    程序集版本:4.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.ComponentModel.TypeConverter
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
Microsoft.VisualBasic.Core
    程序集版本:11.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Memory
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Numerics.Vectors
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
Microsoft.Win32.SystemEvents
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Collections.NonGeneric
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
MadMilkman.Ini
    程序集版本:1.0.6.0
    Win32 版本:不可用
    代码库:
----------------------------------------
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Linq
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Linq.Expressions
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Text.Encoding.CodePages
    程序集版本:8.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Runtime.Loader
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Windows.Forms.resources
    程序集版本:6.0.2.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Text.RegularExpressions
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Collections.Concurrent
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Threading.ThreadPool
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Private.Uri
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Diagnostics.StackTrace
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Reflection.Metadata
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Collections.Immutable
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.IO.MemoryMappedFiles
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Text.Encoding.Extensions
    程序集版本:6.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------

************** JIT 调试 **************
